ClubAdministration/Controllers/system/groupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using ClubAdministration.Library.Core.Pages;
using ClubAdministration.Models;
using ClubAdministration.Models.system;
using ClubAdministration.Models.ViewModels;

namespace ClubAdministration.Controllers.system
{
    public partial class groupsController : BaseController
    {
        //private clubAdminProxy db = new clubAdminProxy();

        // GET: groups
        [HttpGet]
        public ActionResult Index()
        {
            //TODO: This action needs to be optimized, because it fetchs all records from the db and then try to filter the result in app
            return View(db.groups
                .Where(a => a.title .Contains(this.Setting.PageSetting.SearchItem)));
        }

        [HttpPost]
        [ActionName("Index")]
        [ValidateAntiForgeryToken]
        public ActionResult IndexPostBack()
        {
            return this.Index();
        }

        // GET: groups/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                Session["TACTION_RESULT"] = "مشكل در نمايش گروه وجود دارد";
                return this.RedirectToAction("Index");
            }
            var group = db.groups.Find(id);

            if (group == null)
            {
                Session["TACTION_RESULT"] = "گروه درخواستي در سيستم ثبت نشده است";
                return this.RedirectToAction("Index");
            }

            return View(group);
        }

        // GET: groups/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: groups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,title")] groups group)
        {

            //1. Convert the entry to Db Model
            if (ModelState.IsValid == true)
            {
                //TODO: This action need to be deeply reviewed
                db.groups.Add(group);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(group);
        }

        // GET: groups/Edit/5
        public ActionResult Edit(int? id)
        {
            //TODO: This action need to be deeply reviewed
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var entry = db.groups.Find(id);
            return View(entry);
        }

        // POST: groups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,title")] groups group)
        {
            //TODO: This action need to be deeply reviewed
            if (ModelState.IsValid)
            {
                db.Entry(group).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(group);
        }

        // GET: groups/Delete/5
        public ActionResult Delete(int? id)
        {
            //TODO: This action need to be deeply reviewed
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            groups group = db.groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // POST: groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //TODO: This action need to be deeply reviewed
            var group = db.groups.Find(id);
            db.groups.Remove(group);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

ClubAdministration/Controllers/system/menusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using ClubAdministration.Library.Core.Pages;
using ClubAdministration.Models;
using ClubAdministration.Models.system;
using ClubAdministration.Models.ViewModels;

namespace ClubAdministration.Controllers.system
{
    public partial class menusController : BaseController
    {
        //private clubAdminProxy db = new clubAdminProxy();

        // GET: menus
        [HttpGet]
        public ActionResult Index()
        {
            //TODO: This action needs to be optimized, because it fetchs all records from the db and then try to filter the result in app
            return View(db.menu_modules
                .Where(a => a.title.Contains(this.Setting.PageSetting.SearchItem)));
        }

        [HttpPost]
        [ActionName("Index")]
        [ValidateAntiForgeryToken]
        public ActionResult IndexPostBack()
        {
            return this.Index();
        }

        // GET: menus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                Session["TACTION_RESULT"] = "مشكل در نمايش منو وجود دارد";
                return this.RedirectToAction("Index");
            }
            var menu = db.menu_modules.Find(id);

            if (menu == null)
            {
                Session["TACTION_RESULT"] = "منو درخواستي در سيستم ثبت نشده است";
                return this.RedirectToAction("Index");
            }

            return View(menu);
        }

        // GET: menus/Create
        public ActionResult Create()
        {
            //ViewBag.parent = new SelectList(db.menus, "ID", "title");

            return View();
        }

        // POST: menus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,title,menuClass")] menu_modules module)
        {

            //1. Convert the entry to Db Model
            if (ModelState.IsValid == true)
            {
                //TODO: This action need to be deeply reviewed
                db.menu_modules.Add(module);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(module);
        }

        // GET: menus/Edit/5
        public ActionResult Edit(int? id)
        {
            //TODO: This action need to be deeply reviewed
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var entry = db.menu_modules.Find(id);

           //ViewBag.parent = new SelectList(db.menus, "ID", "title", entry.parent);

            return View(entry);
        }

        // POST: menus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,title,menuClass")] menu_modules module)
        {
            //TODO: This action need to be deeply reviewed
            if (ModelState.IsValid)
            {
                db.Entry(module).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(module);
        }

        // GET: menus/Delete/5
        public ActionResult Delete(int? id)
        {
            //TODO: This action need to be deeply reviewed
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            menu_modules module = db.menu_modules.Find(id);
            if (module == null)
            {
                return HttpNotFound();
            }
            bool chiddefault = db.menus.Any(a => a.module_id == module.ID && a.isDefault);

            if (chiddefault)
            {
                Session["TACTION_RESULT"] = "امكان حذف منو پيش فرض وجود ندارد. يكي از آيتم هاي منو انتخابي براي پيش فرض نرم افزار انتخاب شده است.";
                return RedirectToAction("Index");
            }
            return View(module);
        }

        // POST: menus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //TODO: This action need to be deeply reviewed
            var module = db.menu_modules.Find(id);
            db.menu_modules.Remove(module);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

ClubAdministration/Controllers/system/permissionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using ClubAdministration.Library.Core.Pages;
using ClubAdministration.Models;
using ClubAdministration.Models.system;
using ClubAdministration.Models.ViewModels;

namespace ClubAdministration.Controllers.system
{
    public partial class permissionsController : BaseController
    {
        //private clubAdminProxy db = new clubAdminProxy();

        // GET: permissions
        [HttpGet]
        public ActionResult Index()
        {
            //TODO: This action needs to be optimized, because it fetchs all records from the db and then try to filter the result in app
            return View(db.permissions
                .Where(a => a.title.Contains(this.Setting.PageSetting.SearchItem) ||
                a.command.Contains(this.Setting.PageSetting.SearchItem)).Include(a => a.service).Include(a => a.zone));
        }

        [HttpPost]
        [ActionName("Index")]
        [ValidateAntiForgeryToken]
        public ActionResult IndexPostBack()
        {
            return this.Index();
        }

        // GET: permissions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                Session["TACTION_RESULT"] = "مشكل در نمايش دسترسي وجود دارد";
                return this.RedirectToAction("Index");
            }

            var permission = db.permissions.Where(a => a.ID == id).Include(a => a.service).Include(a => a.zone).FirstOrDefault();

            if (permission == null)
            {
                Session["TACTION_RESULT"] = "دسترسي درخواستي در سيستم ثبت نشده است";
                return this.RedirectToAction("Index");
            }

            return View(permission);
        }

        // GET: permissions/Create
        public ActionResult Create()
        {
            ViewBag.parent = new SelectList(db.permissions.ToList(), "ID", "title");
            ViewBag.zones = new SelectList(db.zones.ToList(), "ID", "title");
            ViewBag.services = new SelectList(db.services.ToList(), "ID", "title");
            return View();
        }

        // POST: permissions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,title,parent,command,zone_id,service_id")] permissions permission)
        {

            //1. Convert the entry to Db Model
            if (ModelState.IsValid == true)
            {
                //TODO: This action need to be deeply reviewed
                db.permissions.Add(permission);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(permission);
        }


        // GET: permissions/Edit/5
        public ActionResult Edit(int? id)
        {
            //TODO: This action need to be deeply reviewed
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var entry = db.permissions.Find(id);

            ViewBag.parent = new SelectList(db.permissions.ToList(), "ID", "title", entry.parent);
            ViewBag.zones = new SelectList(db.zones.ToList(), "ID", "title", entry.zone_id);
            ViewBag.services = new SelectList(db.services.ToList(), "ID", "title", entry.service_id);

            return View(entry);
        }

        // POST: permissions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,title,parent,command,zone_id,service_id")] permissions permission)
        {
            //TODO: This action need to be deeply reviewed
            if (ModelState.IsValid)
            {
                db.Entry(permission).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(permission);
        }

        // GET: permissions/Delete/5
        public ActionResult Delete(int? id)
        {
            //TODO: This action need to be deeply reviewed
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            permissions permission = db.permissions.Where(a => a.ID == id).Include(a => a.service).Include(a => a.zone).FirstOrDefault();
            if (permission == null)
            {
                return HttpNotFound();
            }
            return View(permission);
        }

        // POST: permissions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //TODO: This action need to be deeply reviewed
            var permission = db.permissions.Find(id);
            db.permissions.Remove(permission);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

ClubAdministration/Controllers/system/systemController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using ClubAdministration.Library.Core.Pages;
using ClubAdministration.Models;
using ClubAdministration.Models.system;
using ClubAdministration.Models.ViewModels;

namespace ClubAdministration.Controllers.system
{
    public partial class systemController : BaseController
    {
        //private clubAdminProxy db = new clubAdminProxy();

        // GET: system
        [HttpGet]
        public ActionResult Index()
        {
            var security_overview = new security_overviews()
            {
                groups = db.groups.Take(10).ToList(),
                roles = db.roles.Take(10).ToList(),
                permissions = db.permissions.Take(10).ToList()
            };
            //TODO: This action needs to be optimized, because it fetchs all records from the db and then try to filter the result in app
            return View(security_overview);
        }

        public JsonResult getPermissions()
        {
            var permissions = db.permissions.Take(10);
            return new JsonResult { Data = permissions, JsonRequestBehavior=JsonRequestBehavior.AllowGet };
        }

        public JsonResult getRoles()
        {
            var roles = db.roles.Take(10);
            return new JsonResult { Data = roles, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult getGroups()
        {
            var groups = db.groups.Take(10);
            return new JsonResult { Data = groups, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

ClubAdministration/Views/system/Index.cshtml
@model ClubAdministration.Models.ViewModels.security_overviews

@{
    ViewBag.Title = "پنل مديريت نرم افزار  " + ViewBag.training;
}

@using (Html.BeginForm("Index", "system", new { id = ViewBag.training_id }, FormMethod.Post, new { id = "trainingsform", name = "trainingsform" }))
{
    @Html.AntiForgeryToken()
    @widgets.common.ribbon.Show_Ribbon(Url, "system.dashboard.default", "پنل مديريت نرم افزار  ", null)

    <div class="border rounded p-0 mb-3 mt-2 shadow-sm text-center" style="font-size:0.8em">
        <h2 class="bg-light shadow-sm border-bottom mb-3 rounded-top pt-3 pb-3">مديريت تنظيمات نرم افزار <span style="font-weight:bold;color:brown">@ViewBag.training</span></h2>
        <div class="px-2 accordion">
            <div class="row my-4">
                <div class="col-12 text-right">
                    <a class="card-link" data-toggle="collapse" href="#club">
                        باشگاه
                    </a>
                    <hr class="my-2 bg-light" />
                </div>
                <div class="col-12">
                    <div class="row" id="club">

                    </div>
                </div>
            </div>
            <div class="row my-4">
                <div class="col-12 text-right">
                    <a class="card-link" data-toggle="collapse" href="#security">
                        امنيت
                    </a>
                    <hr class="my-2 bg-light" />
                </div>
                <div class="col-12">
                    <div class="row show" id="security">
                        <div class="col-2">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title">كاربران</h5>
                                    <p class="card-text">در اين بخش‌ مديريت كاربران نرم افزار انجام مي شود</p>
                                    <a href="~/users/" class="btn btn-primary">بيشتر...</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title">گروه‌هاي كاربري</h5>
                                    <p class="card-text">در اين بخش‌ مديريت گرو‌هاي كاربري نرم افزار انجام مي‌شود</p>
                                    <a href="~/groups/" class="btn btn-primary">بيشتر...</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title">نقش‌ها</h5>
                                    <p class="card-text">در اين بخش مديريت نقش‌هاي كاربري نرم افزار انجام مي شود</p>
                                    <a href="~/roles/" class="btn btn-primary">بيشتر...</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title">دسترسي‌ها</h5>
                                    <p class="card-text">در اين بخش‌ دسترسي‌هاي كاربري نرم افزار انجام مي شود</p>
                                    <a href="~/permissions/" class="btn btn-primary">بيشتر...</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title">اعطاي دسترسي</h5>
                                    <p class="card-text">در اين بخش‌ مديريت كاربران نرم افزار انجام مي شود</p>
                                    <a href="~/users/" class="btn btn-primary">بيشتر...</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title">عضويت گرو‌ها</h5>
                                    <p class="card-text">در اين بخش‌ مديريت كاربران نرم افزار انجام مي شود</p>
                                    <a href="~/users/" class="btn btn-primary">بيشتر...</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row my-4">
                <div class="col-12 text-right">
                    <a class="card-link" data-toggle="collapse" href="#services">
                        سرويس‌ها
                    </a>
                    <hr class="my-2 bg-light" />
                </div>
                <div class="col-12">
                    <div class="row" id="services">
                        <div class="col-2">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title">منوها</h5>
                                    <p class="card-text">در اين بخش‌ مديريت منوهاي نرم افزار انجام مي شود</p>
                                    <a href="~/menus/" class="btn btn-primary">بيشتر...</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title">قالب‌ها</h5>
                                    <p class="card-text">در اين بخش‌ مديريت قالب‌هاي نرم افزار انجام مي شود</p>
                                    <a href="~/templates/" class="btn btn-primary">بيشتر...</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

ClubAdministration/Views/system/_groupView.cshtml
@model IEnumerable<ClubAdministration.Models.system.groups>

<div id="groupPanel" class="col-2">
    @foreach (var item in Model)
    {
        @Html.ActionLink(item.title, "groups", new { id = item.ID, controller = "groups" })
    }
</div>

ClubAdministration/Views/system/_permissionView.cshtml
@model IEnumerable<ClubAdministration.Models.system.permissions>

<div id="groupPanel" class="col-2">
    @foreach (var item in Model)
    {
        @Html.ActionLink(item.title, "Details", new { id = item.ID, controller = "permissions" })
    }
</div>

ClubAdministration/Views/system/_roleView.cshtml
@model IEnumerable<ClubAdministration.Models.system.roles>

<div id="groupPanel" class="col-2">
    @foreach (var item in Model)
    {
        @Html.ActionLink(item.title, "Details", new { id = item.ID, controller = "roles" })
    }
</div>