ClubAdministration/Models/system/services.cs
namespace ClubAdministration.Models.system
{
    using ClubAdministration.Library.Core.Defaults;
    using ClubAdministration.Library.Utilities;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class services
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        //Things like Ball-Control
        [Required]
        [StringLength(150)]
        public string title { get; set; }

        //name of the application service
        public string name { get; set; }

        //Top level service item
        public int parent { get; set; }
    }
}

ClubAdministration/Controllers/system/servicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using ClubAdministration.Library.Core.Pages;
using ClubAdministration.Models;
using ClubAdministration.Models.system;
using ClubAdministration.Models.ViewModels;

namespace ClubAdministration.Controllers.system
{
    public partial class servicesController : BaseController
    {

        // GET: services
        [HttpGet]
        public ActionResult Index()
        {
            //TODO: This action(services) needs to be optimized, because it fetchs all records from the db and then try to filter the result in app
            return View(db.services
                .Where(a => a.title.Contains(this.Setting.PageSetting.SearchItem) ||
                a.name.Contains(this.Setting.PageSetting.SearchItem))
                );
        }

        [HttpPost]
        [ActionName("Index")]
        [ValidateAntiForgeryToken]
        public ActionResult IndexPostBack()
        {
            return this.Index();
        }

        // GET: services/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                Session["TACTION_RESULT"] = "مشكل در نمايش سرويس وجود دارد";
                return this.RedirectToAction("Index");
            }
            var service = db.services.Find(id);

            if (service == null)
            {
                Session["TACTION_RESULT"] = "سرويس درخواستي در سيستم ثبت نشده است";
                return this.RedirectToAction("Index");
            }

            return View(service);
        }

        // GET: services/Create
        public ActionResult Create()
        {
            var parent = new SelectList(db.services.ToList(), "ID", "title");
            ViewBag.parent = parent;
            return View();
        }

        // POST: groups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,title,name,parent")] services service)
        {

            //1. Convert the entry to Db Model
            if (ModelState.IsValid == true)
            {
                //TODO: This action need to be deeply reviewed
                db.services.Add(service);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(service);
        }

        // GET: services/Edit/5
        public ActionResult Edit(int? id)
        {
            //TODO: This action need to be deeply reviewed
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var entry = db.services.Find(id);
            var parent = new SelectList(db.services.ToList(), "ID", "title",entry.parent);
            ViewBag.parent = parent;
            return View(entry);
        }

        // POST: services/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,title,name,parent")] services service)
        {
            //TODO: This action need to be deeply reviewed
            if (ModelState.IsValid)
            {
                db.Entry(service).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(service);
        }

        // GET: services/Delete/5
        public ActionResult Delete(int? id)
        {
            //TODO: This action need to be deeply reviewed
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            services service = db.services.Find(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            return View(service);
        }

        // POST: services/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //TODO: This action need to be deeply reviewed
            var service = db.services.Find(id);
            db.services.Remove(service);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

ClubAdministration/Views/services/Create.cshtml
@model ClubAdministration.Models.system.services

@{ 
    ViewBag.Title = "ایجاد سرويس";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal p-0 mb-2 shadow-sm">
        <h4 class="bg-light border text-center p-2 py-3 m-0 rounded-top">جزئیات سرويس</h4>
        <div class="container-fluid border rounded-bottom border-top-0 m-0">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group row">
                <div class="col-12 font-weight-bold">
                    @Html.Label("عنوان", htmlAttributes: new { @class = "control-label col" })
                    @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
                </div>
                <div class="col-6 font-weight-bold">
                    @Html.Label("نام(انحصاري)", htmlAttributes: new { @class = "control-label col" })
                    @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                </div>
                <div class="col-6 font-weight-bold">
                    @Html.Label("سرويس بالادستي", htmlAttributes: new { @class = "control-label col" })
                    @Html.DropDownList("parent", null, "يك گزينه را انتخاب كنيد", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.parent, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row border mx-1 rounded">
                <div class="col-sm-12 text-sm-center col-md-6 text-md-left p-0">
                    <input type="submit" value="  ايجاد  " class="btn btn-primary px-5 m-2" />
                </div>
                <div class="col-sm-12 text-sm-left text-md-right col-md-6 p-0">
                    @Html.ActionLink("بازگشت به ليست", "Index", null, new { @class = "btn btn-outline-warning px-5 m-2" })
                </div>
            </div>
        </div>
    </div>
}

ClubAdministration/Views/services/Delete.cshtml
@model ClubAdministration.Models.system.services

@{
    ViewBag.Title = "حذف" + " " + Model.title;
}

@widgets.common.ribbon.Show_Ribbon(Url, "services.delete.default", "آيا از حذف" + (" " + Model.title) + " مطمئن هستيد؟", rootParams: new { id = Model.ID })
@using (Html.BeginForm("Delete", "services", FormMethod.Post, new { @name = "servicesform" }))
{
    @Html.AntiForgeryToken()
    <div class="mt-2 rounded-bottom shadow-sm mb-4">
        <h3 class="text-center rounded-top p-3 border bg-light m-0">اطلاعات پايه</h3>
        <div class="rounded-bottom px-2 py-2 border border-top-0 ">
            <table class="table table-striped table-responsive-sm">
                <tr>
                    <td>
                        كد شناسايي
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.ID)
                    </td>
                </tr>
                <tr>
                    <td>
                        عنوان
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.title)
                    </td>
                </tr>
                <tr>
                    <td>
                        نام
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.name)
                    </td>
                </tr>
            </table>
        </div>
    </div>
}

ClubAdministration/Views/services/Details.cshtml
@model ClubAdministration.Models.system.services

@widgets.common.ribbon.Show_Ribbon(Url, "services.details.default", "جزئيات سرويس " + (" " + Model.title), rootParams: new { id = Model.ID })

<div class="mt-2 rounded-bottom shadow-sm mb-4">
    <h3 class="text-center rounded-top p-3 border bg-light m-0">اطلاعات پايه</h3>
    <div class="rounded-bottom px-2 py-2 border border-top-0 ">
        <table class="table table-striped table-responsive-sm">
            <tr>
                <td>
                    كد شناسايي
                </td>
                <td>
                    @Html.DisplayFor(model => model.ID)
                </td>
            </tr>
            <tr>
                <td>
                    عنوان
                </td>
                <td>
                    @Html.DisplayFor(model => model.title)
                </td>
            </tr>
            <tr>
                <td>
                    نام
                </td>
                <td>
                    @Html.DisplayFor(model => model.name)
                </td>
            </tr>
        </table>
    </div>
</div>

ClubAdministration/Views/services/Edit.cshtml
@model ClubAdministration.Models.system.services

@{ 
    ViewBag.Title = "ويرايش " + Model.title;
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ID)
    <div class="form-horizontal p-0 mb-2 shadow-sm">
        <h4 class="bg-light border text-center p-2 py-3 m-0 rounded-top">جزئیات سرويس</h4>
        <div class="container-fluid border rounded-bottom border-top-0 m-0">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group row">
                <div class="col-12 font-weight-bold">
                    @Html.Label("عنوان", htmlAttributes: new { @class = "control-label col" })
                    @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
                </div>
                <div class="col-6 font-weight-bold">
                    @Html.Label("نام(انحصاري)", htmlAttributes: new { @class = "control-label col" })
                    @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                </div>
                <div class="col-6 font-weight-bold">
                    @Html.Label("سرويس بالادستي", htmlAttributes: new { @class = "control-label col" })
                    @Html.DropDownList("parent", null, "يك گزينه را انتخاب كنيد", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.parent, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row border mx-1 rounded">
                <div class="col-sm-12 text-sm-center col-md-6 text-md-left p-0">
                    <input type="submit" value="  ذخيره  " class="btn btn-primary px-5 m-2" />
                </div>
                <div class="col-sm-12 text-sm-left text-md-right col-md-6 p-0">
                    @Html.ActionLink("بازگشت به ليست", "Index", null, new { @class = "btn btn-outline-warning px-5 m-2" })
                </div>
            </div>
        </div>
    </div>
}

ClubAdministration/Views/services/Index.cshtml
@model IEnumerable<ClubAdministration.Models.system.services>

@{
    ViewBag.Title = "مديريت سرويس‌ها";
}
@using (Html.BeginForm("Index", "services", FormMethod.Post, new { id = "servicesfrm" }))
{
    @widgets.common.ribbon.Show_Ribbon(Url, "services.list.default", "مديريت سرويس‌ها")

    @widgets.common.search.Show_Search_Form(ViewBag.search)

    @Html.AntiForgeryToken();

    <div class="border rounded p-0 mb-3 mt-2 shadow-sm text-center" style="font-size:0.8em">
        <h2 class="bg-light shadow-sm border-bottom mb-3 rounded-top pt-3 pb-3">سرويس‌ها</h2>
        <div class="px-2">
            <table class=" table table-hover table-responsive-sm text-center w-100">
                <thead class="thead-dark">
                    <tr>
                        <th>
                            @Html.CheckBox("IDService", new { @id = "chkwhole" })
                        </th>
                        <th class="d-none d-lg-table-cell d-md-table-cell text-center">
                            #
                        </th>
                        <th class="d-sm-table-cell text-center">
                            سرويس‌
                        </th>
                        <th class="d-sm-table-cell text-center">
                            نام‌
                        </th>
                        <th class="d-sm-table-cell d-md-none d-lg-none d-xl-none text-center">
                            عمليات
                        </th>
                    </tr>
                </thead>
                @{
                    int indexe = 1;
                }
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.CheckBox("IDS", new { @value = item.ID.ToString(), @class = "chkitem", @id = "chkitem" + (indexe) })
                        </td>
                        <th class="d-none d-lg-table-cell d-md-table-cell text-center">
                            @(indexe++)
                        </th>
                        <td class="d-sm-table-cell text-center">
                            @(item.title)
                        </td>
                        <td class="d-sm-table-cell text-center">
                            @(item.name)
                        </td>
                        <td class="d-sm-table-cell d-md-none d-lg-none d-xl-none text-center">
                            @Html.ActionLink("ويرايش", "Edit", new { id = item.ID }) |
                            @Html.ActionLink("نمايش", "Details", new { id = item.ID }) |
                            @Html.ActionLink("حذف", "Delete", new { id = item.ID })
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
}
<script>
    $("#chkwhole").change(function chang() {
        $(".chkitem").not("#chkwhole").prop('checked', this.checked);
        if (this.checked) {
            $(".chkitem").parent().parent().addClass("table-primary");
            $(".chkitem").parent().parent().removeClass("table-light");
        }
        else {
            $(".chkitem").parent().parent().removeClass("table-primary");
            $(".chkitem").parent().parent().addClass("table-light");
        }
    });

    $(".chkitem").change(function chng() {
        if (this.checked) {
            $(this.parentElement.parentElement).addClass("table-primary");
            $(this.parentElement.parentElement).removeClass("table-light");
        }
        else {
            $(this.parentElement.parentElement).removeClass("table-primary");
            $(this.parentElement.parentElement).addClass("table-light");
        }
    });

</script>