ClubAdministration/Models/coaches/certificates_issuer.cs
namespace ClubAdministration.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class certificates_issuer
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        [Required]
        [StringLength(250)]
        public string title { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<coach_certificates> certificates { get; set; }
    }
}

ClubAdministration/Models/coaches/certificates_levels.cs
namespace ClubAdministration.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class certificates_levels
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        [Required]
        [StringLength(250)]
        public string title { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<coach_certificates> certificates { get; set; }
    }
}

ClubAdministration/Models/coaches/coach.cs
namespace ClubAdministration.Models
{
    using ClubAdministration.Library.Core.Defaults;
    using ClubAdministration.Library.Utilities;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class coach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public coach()
        {
            coach_certificates = new HashSet<coach_certificates>();
        }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        [Required]
        [MaxLength(50)]
        public string coach_name { get; set; }

        [Required]
        [MaxLength(50)]
        public string coach_family { get; set; }

        public Int64 coach_bdate { get; set; }

        [NotMapped]
        public string coach_birthdate
        {
            get
            {
                return DateConvertor.ConvertToPersian(BaseDate.GetDateFromDateOffsetSystemStartDate(this.coach_bdate).ToString());
            }
            set
            {
                this.coach_bdate = BaseDate.CalculateDateDiffInMinutes(value);
            }
        }

        public int coach_gender { get; set; }

        public Int64 reg_date { get; set; }

        [NotMapped]
        public string registeration_date 
        {
            get
            {
                return DateConvertor.ConvertToPersian(BaseDate.GetDateFromDateOffsetSystemStartDate(this.reg_date).ToString());
            }
            set
            {
                this.reg_date = BaseDate.CalculateDateDiffInMinutes(value);
            }
        }

        [NotMapped]
        public string FullName {
            get 
            {
                return this.coach_name + " " + this.coach_family;
            }
        }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<coach_certificates> coach_certificates { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<coach_training> coach_trainings { get; set; }
    }
}

ClubAdministration/Models/coaches/coach_session.cs
namespace ClubAdministration.Models
{
    using ClubAdministration.Library.Core.Defaults;
    using ClubAdministration.Library.Utilities;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class coach_sessions
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        public int coach_id { get; set; }

        public int session_id { get; set; }

        [ForeignKey("coach_id")]
        public virtual coach coach { get; set; }

        [ForeignKey("session_id")]
        public virtual training_sessions session { get; set; }
    }
}

ClubAdministration/Controllers/club/trainingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClubAdministration.Library.Core.Defaults;
using ClubAdministration.Library.Core.Pages;
using ClubAdministration.Library.Utilities;
using ClubAdministration.Models;
using ClubAdministration.Resources.modules.club;

namespace ClubAdministration.Controllers
{
    public partial class trainingsController : BaseController
    {
        //private clubAdminProxy db = new clubAdminProxy();

        // GET: trainingsController
        [HttpGet]
        public ActionResult Index()
        {
            //TODO: This action needs to be optimized, because it fetchs all records from the db and then try to filter the result in app
            return View(db.training_terms.Include(a => a.agelevel).ToList().Where(a => 
            a.term_title.Contains(this.Setting.PageSetting.SearchItem)||
            a.start_date.Contains(this.Setting.PageSetting.SearchItem)||
            a.end_date.Contains(this.Setting.PageSetting.SearchItem)
            ).ToList());
        }

        [HttpPost]
        [ActionName("Index")]
        [ValidateAntiForgeryToken]
        public ActionResult IndexPostBack()
        {
            return this.Index();
        }

        public ActionResult Sessions(int? id)
        {
            if (id == null)
            {
                
                Session["TACTION_RESULT"] = lang.sessionShowError;
                return this.RedirectToAction("Index");
            }
            training_terms training_terms = db.training_terms.Find(id);
            if (training_terms == null)
            {
                Session["TACTION_RESULT"] = lang.sessionNotFound;
                return this.RedirectToAction("Index");
            }

            ViewBag.training = training_terms;

            return View(training_terms.training_sessions.Where(a => a.session_date.Contains(this.Setting.PageSetting.SearchItem)).ToList());
        }
        [HttpPost]
        [ActionName("Sessions")]
        [ValidateAntiForgeryToken]
        public ActionResult SessionsPostBack(int? id)
        {
            return this.Sessions(id);
        }

        public ActionResult Coaches(int? id)
        {
            if (id == null)
            {
                Session["TACTION_RESULT"] = lang.coachShowError;
                return this.RedirectToAction("Index");
            }
            training_terms training_terms = db.training_terms.Find(id);
            if (training_terms == null)
            {
                Session["TACTION_RESULT"] = lang.coachNotFound;
                return this.RedirectToAction("Index");
            }

            ViewBag.training = training_terms;

            return View(training_terms.coach_training.Where(a => a.coach.coach_name.Contains(this.Setting.PageSetting.SearchItem) ||
            a.coach.coach_family.Contains(this.Setting.PageSetting.SearchItem)
            ).ToList());
        }
        [HttpPost]
        [ActionName("Coaches")]
        [ValidateAntiForgeryToken]
        public ActionResult CoachesPostBack(int? id)
        {
            return this.Coaches(id);
        }

        public ActionResult Players(int? id)
        {
            if (id == null)
            {
                Session["TACTION_RESULT"] = lang.playerShowError;
                return this.RedirectToAction("Index");
            }
            training_terms training_terms = db.training_terms.Find(id);
            if (training_terms == null)
            {
                Session["TACTION_RESULT"] = lang.playerNotFound;
                return this.RedirectToAction("Index");
            }

            ViewBag.training = training_terms;

            return View(training_terms.player_registerations
                .Where(a =>
                a.player.name.Contains(this.Setting.PageSetting.SearchItem)
                || a.player.familiy.Contains(this.Setting.PageSetting.SearchItem)
                ).ToList());
        }
        [HttpPost]
        [ActionName("Players")]
        [ValidateAntiForgeryToken]
        public ActionResult PlayersPostBack(int? id)
        {
            return this.Players(id);
        }

        // GET: trainings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                Session["TACTION_RESULT"] = lang.trainingShowError;
                return this.RedirectToAction("Index");
            }
            training_terms training_terms = db.training_terms.Where(a => a.ID == id).Include(a => a.agelevel).FirstOrDefault();
            if (training_terms == null)
            {
                Session["TACTION_RESULT"] = lang.trainingNotFound;
                return this.RedirectToAction("Index");
            }

            return View(training_terms);
        }

        // GET: trainings/Create
        public ActionResult Create()
        {
            //TODO: This action need to be deeply reviewed
            ViewBag.level_id = new SelectList(db.agelevels.ToList(), "ID", "level");
            return View();
        }

        // POST: clubController/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,term_title,start_date,max_player,session_per_week,weekdays,active,end_date,fee_type,level_id,start_time,end_time")] training_terms training_terms)
        {
            //TODO: This action need to be deeply reviewed
            if (ModelState.IsValid)
            {
                db.training_terms.Add(training_terms);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(training_terms);
        }

        // GET: trainings/Edit/5
        public ActionResult Edit(int? id)
        {
            //TODO: This action need to be deeply reviewed
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            training_terms training_terms = db.training_terms.Find(id);

            if (training_terms == null)
            {
                return HttpNotFound();
            }
            ViewBag.level_id = new SelectList(db.agelevels.ToList(), "ID", "level", training_terms.level_id);

            return View(training_terms);
        }

        // POST: trainings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,term_title,start_date,max_player,session_per_week,weekdays,active,end_date,fee_type,level_id,start_time,end_time")] training_terms training_terms)
        {
            //TODO: This action need to be deeply reviewed
            if (ModelState.IsValid)
            {
                db.Entry(training_terms).State = EntityState.Modified;
                db.SaveChanges();
                //TODO : cascade update on players end subscriptions for the players whose subscription dates not passed
                return RedirectToAction("Index");
            }
            return View(training_terms);
        }

        // GET: trainings/Delete/5
        public ActionResult Delete(int? id)
        {
            //TODO: This action need to be deeply reviewed
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            training_terms training_terms = db.training_terms.Where(a => a.ID == id).Include(a => a.agelevel).FirstOrDefault();
            if (training_terms == null)
            {
                return HttpNotFound();
            }

            return View(training_terms);
        }

        // POST: trainings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //TODO: This action need to be deeply reviewed
            training_terms training_terms = db.training_terms.Find(id);
            db.training_terms.Remove(training_terms);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

ClubAdministration/Controllers/coaches/coachesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClubAdministration.Library.Core.Pages;
using ClubAdministration.Models;

namespace ClubAdministration.Controllers.coaches
{
    public partial class coachesController : BaseController
    {
        //private clubAdminProxy db = new clubAdminProxy();

        // GET: coaches
        public ActionResult Index()
        { 
            return View(db.coaches.ToList().Where(
                a => a.FullName.Contains(this.Setting.PageSetting.SearchItem)).ToList());
        }

        // POST: coaches
        [HttpPost,ActionName("Index"),ValidateAntiForgeryToken]
        public ActionResult IndexPostBack()
        {
            return Index();
        }


        // GET: coaches/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            coach coach = db.coaches.Find(id);
            if (coach == null)
            {
                return HttpNotFound();
            }
            return View(coach);
        }

        // GET: coaches/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: coaches/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,coach_name,coach_family,coach_birthday,coach_gender,registeration_date")] coach coach)
        {
            if (ModelState.IsValid)
            {
                db.coaches.Add(coach);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(coach);
        }

        // GET: coaches/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            coach coach = db.coaches.Find(id);
            if (coach == null)
            {
                return HttpNotFound();
            }
            return View(coach);
        }

        // POST: coaches/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,coach_name,coach_family,coach_birthday,coach_gender,registeration_date")] coach coach)
        {
            if (ModelState.IsValid)
            {
                db.Entry(coach).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(coach);
        }

        // GET: coaches/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            coach coach = db.coaches.Find(id);
            if (coach == null)
            {
                return HttpNotFound();
            }
            return View(coach);
        }

        // POST: coaches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            coach coach = db.coaches.Find(id);
            db.coaches.Remove(coach);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ClubAdministration/Views/coaches/Certificates.cshtml
@model IEnumerable<ClubAdministration.Models.coach_certificates>
@{
    var coach = (ClubAdministration.Models.coach)ViewBag.coach;
    ViewBag.Title = "ليست مدرك‌هاي مربي‌گري  " + coach.FullName;
}

@using (Html.BeginForm("Certificates", "coaches", new { id = coach.ID }, FormMethod.Post, new { id = "coachform", name = "coachform" }))
{
    @Html.AntiForgeryToken()
    @widgets.common.ribbon.Show_Ribbon(Url, "coaches.certificates.default", "مديريت مدارك مربي‌گري", new { id = coach.ID })

    @widgets.common.search.Show_Search_Form(ViewBag.search)

    <div class="border rounded p-0 mb-3 mt-2 shadow-sm text-center" style="font-size:0.8em">
        <h2 class="bg-light shadow-sm border-bottom mb-3 rounded-top pt-3 pb-3">مدارك مربيگري <span style="font-weight:bold;color:brown">@coach.FullName</span></h2>
        <div class="px-2">
            <table class=" table table-hover table-responsive-sm text-center w-100">
                <thead class="thead-dark">
                    <tr>
                        <th>
                            @Html.CheckBox("IDSubscription", new { @id = "chkwhole" })
                        </th>
                        <th>
                            #
                        </th>
                        <th>
                            عنوان مدرك
                        </th>
                        <th>
                            تاريخ اخذ مدرك
                        </th>
                        <th>
                            تاريخ انقضا
                        </th>
                        <th>
                            صادركننده
                        </th>
                        <th>
                            درجه
                        </th>
                        <th class="d-sm-table-cell d-md-none d-lg-none d-xl-none text-center">
                            عمليات
                        </th>
                    </tr>
                </thead>
                @{
                    int index = 1;
                }
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.CheckBox("IDS", new { @value = item.ID.ToString(), @class = "chkitem", @id = "chkitem" + (index) })
                        </td>
                        <th>
                            @Html.Label((index++).ToString())
                        </th>
                        <td>
                            @item.certificate_title
                        </td>
                        <td>
                            @item.certificate_date
                        </td>
                        <td>
                            @item.certificate_expiredate
                        </td>
                        <td>
                            @item.issuer.title
                        </td>
                        <td>
                            @item.level.title
                        </td>
                        <td class="d-sm-table-cell d-md-none d-lg-none d-xl-none text-center">
                            @Html.ActionLink("انصراف مربي", "DeleteCertificate", new { id = item.ID }) |
                            @Html.ActionLink("ويرايش عضويت", "EditCertificate", new { id = item.ID }) |
                            @Html.ActionLink("جزئيات", "DetailsCertificate", new { id = item.ID })

                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
}
<script>
        $("#chkwhole").change(function chang() {
            $(".chkitem").not("#chkwhole").prop('checked', this.checked);
            if (this.checked) {
                $(".chkitem").parent().parent().addClass("table-primary");
                $(".chkitem").parent().parent().removeClass("table-light");
            }
            else {
                $(".chkitem").parent().parent().removeClass("table-primary");
                $(".chkitem").parent().parent().addClass("table-light");
            }
        });

        $(".chkitem").change(function chng() {
            if (this.checked) {
                $(this.parentElement.parentElement).addClass("table-primary");
                $(this.parentElement.parentElement).removeClass("table-light");
            }
            else {
                $(this.parentElement.parentElement).removeClass("table-primary");
                $(this.parentElement.parentElement).addClass("table-light");
            }
        });

</script>

ClubAdministration/Views/coaches/CreateLevel.cshtml
@model ClubAdministration.Models.certificates_levels

@{ 
    ViewBag.Title = "ایجاد درجه مدرك";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal p-0 mb-2 shadow-sm">
        <h4 class="bg-light border text-center p-2 py-3 m-0 rounded-top">جزئیات درجه</h4>
        <div class="container-fluid border rounded-bottom border-top-0 m-0">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group row">
                <div class="col font-weight-bold">
                    @Html.Label("نام درجه", htmlAttributes: new { @class = "control-label col" })
                    @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.title , "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row border mx-1 rounded">
                <div class="col-sm-12 text-sm-center col-md-6 text-md-left p-0">
                    <input type="submit" value="  ايجاد  " class="btn btn-primary px-5 m-2" />
                </div>
                <div class="col-sm-12 text-sm-left text-md-right col-md-6 p-0">
                    @Html.ActionLink("بازگشت به ليست", "Levels", null, new { @class = "btn btn-outline-warning px-5 m-2" })
                </div>
            </div>
        </div>
    </div>
}

ClubAdministration/Views/coaches/DeleteIssuer.cshtml
@model ClubAdministration.Models.certificates_issuer

@{
    ViewBag.Title = "حذف" + " " + Model.title;
}

@widgets.common.ribbon.Show_Ribbon(Url, "coaches.issuers.delete", "آيا از حذف" + (" " + Model.title) + " مطمئن هستيد؟", rootParams: new { id = Model.ID })
@using (Html.BeginForm("DeleteIssuer", "coaches", FormMethod.Post, new { @name = "issuerform" }))
{
    @Html.AntiForgeryToken()
    <div class="mt-2 rounded-bottom shadow-sm mb-4">
        <h3 class="text-center rounded-top p-3 border bg-light m-0">اطلاعات پايه</h3>
        <div class="rounded-bottom px-2 py-2 border border-top-0 ">
            <table class="table table-striped table-responsive-sm">
                <tr>
                    <td>
                        كد شناسايي
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.ID)
                    </td>
                </tr>
                <tr>
                    <td>
                        صادركننده
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.title)
                    </td>
                </tr>
            </table>
        </div>
    </div>
}

ClubAdministration/Views/coaches/DeleteLevel.cshtml
@model ClubAdministration.Models.certificates_levels

@{
    ViewBag.Title = "حذف" + " " + Model.level;
}

@widgets.common.ribbon.Show_Ribbon(Url, "coaches.levels.delete", "آيا از حذف" + (" " + Model.title) + " مطمئن هستيد؟", rootParams: new { id = Model.ID })
@using (Html.BeginForm("DeleteLevel", "coaches", FormMethod.Post, new { @name = "levelform" }))
{
    @Html.AntiForgeryToken()
    <div class="mt-2 rounded-bottom shadow-sm mb-4">
        <h3 class="text-center rounded-top p-3 border bg-light m-0">اطلاعات پايه</h3>
        <div class="rounded-bottom px-2 py-2 border border-top-0 ">
            <table class="table table-striped table-responsive-sm">
                <tr>
                    <td>
                        كد شناسايي
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.ID)
                    </td>
                </tr>
                <tr>
                    <td>
                        درجه
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.title)
                    </td>
                </tr>
            </table>
        </div>
    </div>
}

ClubAdministration/Views/coaches/DetailsLevel.cshtml
@model ClubAdministration.Models.certificates_levels

@widgets.common.ribbon.Show_Ribbon(Url, "coaches.levels.details", "جزئيات درجه " + (" " + Model.title), rootParams: new { id = Model.ID })

<div class="mt-2 rounded-bottom shadow-sm mb-4">
    <h3 class="text-center rounded-top p-3 border bg-light m-0">اطلاعات پايه</h3>
    <div class="rounded-bottom px-2 py-2 border border-top-0 ">
        <table class="table table-striped table-responsive-sm">
            <tr>
                <td>
                    كد شناسايي
                </td>
                <td>
                    @Html.DisplayFor(model => model.ID)
                </td>
            </tr>
            <tr>
                <td>
                    درجه
                </td>
                <td>
                    @Html.DisplayFor(model => model.title)
                </td>
            </tr>
        </table>
    </div>
</div>

ClubAdministration/Views/coaches/IssuerCertificates.cshtml
@model ICollection<ClubAdministration.Models.coach_certificates>
@{
    var issuer = (ClubAdministration.Models.certificates_issuer)ViewBag.account;
    ViewBag.Title = "مدارك  " + issuer.title;
}
@widgets.common.ribbon.Show_Ribbon(Url, "coaches.issuers.certificates", "مدارك  " + issuer.title, new { id = issuer.ID })
@using (Html.BeginForm("IssuerCertificates", "coaches", FormMethod.Post, new { id = "issuerfrm" }))
{
    @widgets.common.search.Show_Search_Form(ViewBag.search)
    @Html.AntiForgeryToken()
    <div class="border rounded p-0 mb-3 mt-2 shadow-sm text-center" style="font-size:0.8em">
        <h3 class="table-light border border-bottom-0 accordion py-3 m-0 rounded-top shadow-sm">
            مدارك @issuer.title
        </h3>
        <div class="border rounded-bottom p-2 text-center">
            <table class="table text-center table-hover table-bordered table-responsive-sm py-0 m-0">
                <thead class="thead-dark">
                    <tr>
                        <th>
                            @Html.CheckBox("IDIssuers", new { @id = "chkwhole" })
                        </th>
                        <th class="text-center">
                            #
                        </th>
                        <th class="text-center">
                            عنوان مدرك
                        </th>
                        <th class="text-center">
                            دارنده مدرك
                        </th>
                        <th class="d-sm-table-cell d-md-none d-lg-none d-xl-none text-center">
                            عمليات
                        </th>
                    </tr>
                </thead>
                @{
                    int index = 1;
                }
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.CheckBox("IDS", new { @value = item.ID.ToString(), @class = "chkitem", @id = "chkitem" + (index) })
                        </td>
                        <th scope="row">
                            @Html.Label((index++).ToString())
                        </th>
                        <td>
                            @Html.ActionLink(item.certificate_title, "DetailsCertificate", new { Controller = "coaches", id = item.ID })
                        </td>
                        <td>
                            @Html.ActionLink(item.coach.FullName, "Details", new { Controller = "coaches", id = item.coach_id })
                        </td>
                        <td class="d-sm-table-cell d-md-none d-lg-none d-xl-none text-center">
                            @Html.ActionLink("ويرايش", "EditCertificate", new { id = item.ID }) |
                            @Html.ActionLink("جزئيات", "DetailsCertificate", new { id = item.ID }) |
                            @Html.ActionLink("حذف", "DeleteCertificate", new { id = item.ID })
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
}
<script>
    $("#chkwhole").change(function chang() {
        $(".chkitem").not("#chkwhole").prop('checked', this.checked);
        if (this.checked) {
            $(".chkitem").parent().parent().addClass("table-primary");
            $(".chkitem").parent().parent().removeClass("table-light");
        }
        else {
            $(".chkitem").parent().parent().removeClass("table-primary");
            $(".chkitem").parent().parent().addClass("table-light");
        }
    });

    $(".chkitem").change(function chng() {
        if (this.checked) {
            $(this.parentElement.parentElement).addClass("table-primary");
            $(this.parentElement.parentElement).removeClass("table-light");
        }
        else {
            $(this.parentElement.parentElement).removeClass("table-primary");
            $(this.parentElement.parentElement).addClass("table-light");
        }
    });

</script>