ClubAdministration/Models/system/permissions.cs
namespace ClubAdministration.Models.system
{
    using ClubAdministration.Library.Core.Defaults;
    using ClubAdministration.Library.Utilities;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class permissions
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        //Things like Ball-Control
        [Required]
        [StringLength(150)]
        public string title { get; set; }
        public string command { get; set; }
        public int parent { get; set; }

        [ForeignKey("zone_id")]
        public zones zone { get; set; }
        public int zone_id { get; set; }

        [ForeignKey("service_id")]
        public services service { get; set; }
        public int service_id { get; set; }

        public virtual ICollection<role_permissions> roles { get; set; }
    }
}

ClubAdministration/Controllers/system/permissionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using ClubAdministration.Library.Core.Pages;
using ClubAdministration.Models;
using ClubAdministration.Models.system;
using ClubAdministration.Models.ViewModels;

namespace ClubAdministration.Controllers.system
{
    public partial class permissionsController : BaseController
    {
        //private clubAdminProxy db = new clubAdminProxy();

        // GET: permissions
        [HttpGet]
        public ActionResult Index()
        {
            //TODO: This action needs to be optimized, because it fetchs all records from the db and then try to filter the result in app
            return View(db.permissions
                .Where(a => a.title.Contains(this.Setting.PageSetting.SearchItem) ||
                a.command.Contains(this.Setting.PageSetting.SearchItem)).Include(a => a.service).Include(a => a.zone));
        }

        [HttpPost]
        [ActionName("Index")]
        [ValidateAntiForgeryToken]
        public ActionResult IndexPostBack()
        {
            return this.Index();
        }

        // GET: permissions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                Session["TACTION_RESULT"] = "مشكل در نمايش دسترسي وجود دارد";
                return this.RedirectToAction("Index");
            }

            var permission = db.permissions.Where(a => a.ID == id).Include(a => a.service).Include(a => a.zone).FirstOrDefault();

            if (permission == null)
            {
                Session["TACTION_RESULT"] = "دسترسي درخواستي در سيستم ثبت نشده است";
                return this.RedirectToAction("Index");
            }

            return View(permission);
        }

        // GET: permissions/Create
        public ActionResult Create()
        {
            ViewBag.parent = new SelectList(db.permissions.ToList(), "ID", "title");
            ViewBag.zones = new SelectList(db.zones.ToList(), "ID", "title");
            ViewBag.services = new SelectList(db.services.ToList(), "ID", "title");
            return View();
        }

        // POST: permissions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,title,parent,command,zone_id,service_id")] permissions permission)
        {

            //1. Convert the entry to Db Model
            if (ModelState.IsValid == true)
            {
                //TODO: This action need to be deeply reviewed
                db.permissions.Add(permission);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(permission);
        }


        // GET: permissions/Edit/5
        public ActionResult Edit(int? id)
        {
            //TODO: This action need to be deeply reviewed
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var entry = db.permissions.Find(id);

            ViewBag.parent = new SelectList(db.permissions.ToList(), "ID", "title", entry.parent);
            ViewBag.zones = new SelectList(db.zones.ToList(), "ID", "title", entry.zone_id);
            ViewBag.services = new SelectList(db.services.ToList(), "ID", "title", entry.service_id);

            return View(entry);
        }

        // POST: permissions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,title,parent,command,zone_id,service_id")] permissions permission)
        {
            //TODO: This action need to be deeply reviewed
            if (ModelState.IsValid)
            {
                db.Entry(permission).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(permission);
        }

        // GET: permissions/Delete/5
        public ActionResult Delete(int? id)
        {
            //TODO: This action need to be deeply reviewed
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            permissions permission = db.permissions.Where(a => a.ID == id).Include(a => a.service).Include(a => a.zone).FirstOrDefault();
            if (permission == null)
            {
                return HttpNotFound();
            }
            return View(permission);
        }

        // POST: permissions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //TODO: This action need to be deeply reviewed
            var permission = db.permissions.Find(id);
            db.permissions.Remove(permission);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

ClubAdministration/Views/permissions/Create.cshtml
@model ClubAdministration.Models.system.permissions

@{ 
    ViewBag.Title = "ایجاد دسترسي كاربري";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal p-0 mb-2 shadow-sm">
        <h4 class="bg-light border text-center p-2 py-3 m-0 rounded-top">جزئیات دسترسي كاربري</h4>
        <div class="container-fluid border rounded-bottom border-top-0 m-0">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group row">
                <div class="col-4 font-weight-bold">
                    @Html.Label("دسترسي كاربري", htmlAttributes: new { @class = "control-label col" })
                    @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
                </div>
                <div class="col-4 font-weight-bold">
                    @Html.Label("دستور", htmlAttributes: new { @class = "control-label col" })
                    @Html.EditorFor(model => model.command, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.command, "", new { @class = "text-danger" })
                </div>
                <div class="col-4 font-weight-bold">
                    @Html.Label("دسترسي بالادستي", htmlAttributes: new { @class = "control-label col" })
                    @Html.DropDownList("parent", null, "يك گزينه را انتخاب كنيد", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.parent, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4 font-weight-bold">
                    @Html.Label("سرويس", htmlAttributes: new { @class = "control-label col" })
                    @Html.DropDownList("services", null, "يك گزينه را انتخاب كنيد", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.service_id, "", new { @class = "text-danger" })
                </div>
                <div class="col-4 font-weight-bold">
                    @Html.Label("محدوده دسترسي", htmlAttributes: new { @class = "control-label col" })
                    @Html.DropDownList("zones", null, "يك گزينه را انتخاب كنيد", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.zone_id, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row border mx-1 rounded">
                <div class="col-sm-12 text-sm-center col-md-6 text-md-left p-0">
                    <input type="submit" value="  ايجاد  " class="btn btn-primary px-5 m-2" />
                </div>
                <div class="col-sm-12 text-sm-left text-md-right col-md-6 p-0">
                    @Html.ActionLink("بازگشت به ليست", "Index", null, new { @class = "btn btn-outline-warning px-5 m-2" })
                </div>
            </div>
        </div>
    </div>
}

ClubAdministration/Views/permissions/Delete.cshtml
@model ClubAdministration.Models.system.permissions

@{
    ViewBag.Title = "حذف" + " " + Model.title;
}

@widgets.common.ribbon.Show_Ribbon(Url, "permissions.delete.default", "آيا از حذف" + (" " + Model.title) + " مطمئن هستيد؟", rootParams: new { id = Model.ID })
@using (Html.BeginForm("Delete", "permissions", FormMethod.Post, new { @name = "permissionsform" }))
{
    @Html.AntiForgeryToken()
    <div class="mt-2 rounded-bottom shadow-sm mb-4">
        <h3 class="text-center rounded-top p-3 border bg-light m-0">اطلاعات پايه</h3>
        <div class="rounded-bottom px-2 py-2 border border-top-0 ">
            <table class="table table-striped table-responsive-sm">
                <tr>
                    <td>
                        كد شناسايي
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.ID)
                    </td>
                </tr>
                <tr>
                    <td>
                        دسترسي كاربري
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.title)
                    </td>
                </tr>
                <tr>
                    <td>
                        سرويس
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.service.title)
                    </td>
                </tr>
                <tr>
                    <td>
                        محدوده دسترسي
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.zone.title)
                    </td>
                </tr>
            </table>
        </div>
    </div>
}

ClubAdministration/Views/permissions/Details.cshtml
@model ClubAdministration.Models.system.permissions

@widgets.common.ribbon.Show_Ribbon(Url, "permissions.details.default", "جزئيات دسترسي " + (" " + Model.title), rootParams: new { id = Model.ID })

<div class="mt-2 rounded-bottom shadow-sm mb-4">
    <h3 class="text-center rounded-top p-3 border bg-light m-0">اطلاعات پايه</h3>
    <div class="rounded-bottom px-2 py-2 border border-top-0 ">
        <table class="table table-striped table-responsive-sm">
            <tr>
                <td>
                    كد شناسايي
                </td>
                <td>
                    @Html.DisplayFor(model => model.ID)
                </td>
            </tr>
            <tr>
                <td>
                    دسترسي كاربري
                </td>
                <td>
                    @Html.DisplayFor(model => model.title)
                </td>
            </tr>
            <tr>
                <td>
                    سرويس
                </td>
                <td>
                    @Html.DisplayFor(model => model.service.title)
                </td>
            </tr>
            <tr>
                <td>
                    محدوده دسترسي
                </td>
                <td>
                    @Html.DisplayFor(model => model.zone.title)
                </td>
            </tr>
        </table>
    </div>
</div>

ClubAdministration/Views/permissions/Edit.cshtml
@model ClubAdministration.Models.system.permissions

@{ 
    ViewBag.Title = "ويرايش " + Model.title;
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ID)
    <div class="form-horizontal p-0 mb-2 shadow-sm">
        <h4 class="bg-light border text-center p-2 py-3 m-0 rounded-top">جزئیات دسترسي</h4>
        <div class="container-fluid border rounded-bottom border-top-0 m-0">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group row">
                <div class="col-4 font-weight-bold">
                    @Html.Label("دسترسي", htmlAttributes: new { @class = "control-label col" })
                    @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
                </div>
                <div class="col-4 font-weight-bold">
                    @Html.Label("دستور", htmlAttributes: new { @class = "control-label col" })
                    @Html.EditorFor(model => model.command, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.command, "", new { @class = "text-danger" })
                </div>
                <div class="col-4 font-weight-bold">
                    @Html.Label("دسترسي بالادستي", htmlAttributes: new { @class = "control-label col" })
                    @Html.DropDownList("parent", null, "يك گزينه را انتخاب كنيد", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.parent, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4 font-weight-bold">
                    @Html.Label("سرويس", htmlAttributes: new { @class = "control-label col" })
                    @Html.DropDownList("services", null, "يك گزينه را انتخاب كنيد", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.service_id, "", new { @class = "text-danger" })
                </div>
                <div class="col-4 font-weight-bold">
                    @Html.Label("محدوده دسترسي", htmlAttributes: new { @class = "control-label col" })
                    @Html.DropDownList("zones", null, "يك گزينه را انتخاب كنيد", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.zone_id, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row border mx-1 rounded">
                <div class="col-sm-12 text-sm-center col-md-6 text-md-left p-0">
                    <input type="submit" value="  ذخيره  " class="btn btn-primary px-5 m-2" />
                </div>
                <div class="col-sm-12 text-sm-left text-md-right col-md-6 p-0">
                    @Html.ActionLink("بازگشت به ليست", "Index", null, new { @class = "btn btn-outline-warning px-5 m-2" })
                </div>
            </div>
        </div>
    </div>
}

ClubAdministration/Views/permissions/Index.cshtml
@model IEnumerable<ClubAdministration.Models.system.permissions>

@{
    ViewBag.Title = "مديريت دسترسي‌هاي كاربري";
}
@using (Html.BeginForm("Index", "permissions", FormMethod.Post, new { id = "permissionsfrm" }))
{
    @widgets.common.ribbon.Show_Ribbon(Url, "permissions.list.default", "مديريت دسترسي‌هاي كاربري")

    @widgets.common.search.Show_Search_Form(ViewBag.search)

    @Html.AntiForgeryToken();

    <div class="border rounded p-0 mb-3 mt-2 shadow-sm text-center" style="font-size:0.8em">
        <h2 class="bg-light shadow-sm border-bottom mb-3 rounded-top pt-3 pb-3">دسترسي‌هاي كاربري</h2>
        <div class="px-2">
            <table class=" table table-hover table-responsive-sm text-center w-100">
                <thead class="thead-dark">
                    <tr>
                        <th>
                            @Html.CheckBox("IDPermission", new { @id = "chkwhole" })
                        </th>
                        <th class="d-none d-lg-table-cell d-md-table-cell text-center">
                            #
                        </th>
                        <th class="d-sm-table-cell text-center">
                            دسترسي
                        </th>
                        <th class="d-sm-table-cell text-center">
                            سرويس
                        </th>
                        <th class="d-sm-table-cell text-center">
                            محدوده دسترسي
                        </th>
                        <th class="d-sm-table-cell d-md-none d-lg-none d-xl-none text-center">
                            عمليات
                        </th>
                    </tr>
                </thead>
                @{
                    int indexe = 1;
                }
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.CheckBox("IDS", new { @value = item.ID.ToString(), @class = "chkitem", @id = "chkitem" + (indexe) })
                        </td>
                        <th class="d-none d-lg-table-cell d-md-table-cell text-center">
                            @(indexe++)
                        </th>
                        <td class="d-sm-table-cell text-center">
                            @(item.title)
                        </td>
                        <td class="d-sm-table-cell text-center">
                            @(item.service.title)
                        </td>
                        <td class="d-sm-table-cell text-center">
                            @(item.zone.title)
                        </td>
                        <td class="d-sm-table-cell d-md-none d-lg-none d-xl-none text-center">
                            @Html.ActionLink("ويرايش", "Edit", new { id = item.ID }) |
                            @Html.ActionLink("نمايش", "Details", new { id = item.ID }) |
                            @Html.ActionLink("حذف", "Delete", new { id = item.ID })
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
}
<script>
    $("#chkwhole").change(function chang() {
        $(".chkitem").not("#chkwhole").prop('checked', this.checked);
        if (this.checked) {
            $(".chkitem").parent().parent().addClass("table-primary");
            $(".chkitem").parent().parent().removeClass("table-light");
        }
        else {
            $(".chkitem").parent().parent().removeClass("table-primary");
            $(".chkitem").parent().parent().addClass("table-light");
        }
    });

    $(".chkitem").change(function chng() {
        if (this.checked) {
            $(this.parentElement.parentElement).addClass("table-primary");
            $(this.parentElement.parentElement).removeClass("table-light");
        }
        else {
            $(this.parentElement.parentElement).removeClass("table-primary");
            $(this.parentElement.parentElement).addClass("table-light");
        }
    });

</script>